### PR TITLE
Remove test running scripts.

### PR DESCRIPTION
**Pull request by utkarshayachit**
Use cmake to add tests with different command line options instead of using bash scripts.
This makes it easier to have platform independent tests.

### CODE REVIEW

**Comment by utkarshayachit** [comment]
@mrzv this is preparation for the windows build fixes. This ensures that tests can run on windows too.

**Comment by utkarshayachit** [comment]
@mrzv not sure why `io-test` failed on `macOS+openmpi`. Any ideas?

**Comment by mrzv** [comment]
@utkarshayachit Just a note that I'm not ignoring this. I tried your tests on my (Mac) laptop, and `io-test` with OpenMPI passed. So I'm not quite sure what's going on. On the other hand, another test failed, but I know why — that one doesn't matter.

I'm mildly tempted to disable that particular set of tests (Mac + OpenMPI), but that's, of course, the wrong way to go about the problem.

**Comment by utkarshayachit** [comment]
thanks, @mrzv

**Comment by mrzv** [comment]
#56 added your commit, together with fixes to testing to make Travis pass. I'm not quite sure why this pull request is still showing changes with master. I'm going to close this PR, but @utkarshayachit can you verify that these changes are on the master branch?

**Comment by utkarshayachit** [comment]
yes, my changes did indeed make it into `master`. thanks.

**Pull request closed without merging**
