### PR TITLE
Fix build on mach-based OS which are not OS X

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by mrzv** [comment]
Thanks for the pull request. All the DIY development actually happens on [Kitware's GitLab](https://gitlab.kitware.com/diatomic/diy). Could you please move this pull request there?

**Comment by sthibaul** [comment]
Done so.
It would be useful to close the merge request support here, since README points to here, not there.

**Comment by mrzv** [comment]
That's a good idea. I'll update the README.

**Comment by mrzv** [comment]
Apparently, there is no way to disable merge requests. But I will add a link to GitLab to the README.

**Pull request closed without merging**
