### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by mrzv**
Retrying @mathstuf's PR. (I screwed up a rebase previously.)

### CODE REVIEW

**Comment by mrzv** [comment]
Hm, perhaps the problem wasn't with the rebase, but with Travis. @mathstuf Can you verify that this is the same changes as were in your PR #58? For some reason, Travis is failing now.

**Comment by mathstuf** [comment]
Diffing the net changes, I'm only seeing context changes between these two.

**Comment by mrzv** [comment]
What do you mean by context changes?

**Comment by mathstuf** [comment]
Only lines starting with `index` or `@@`. "Metadata" is probably more accurate.

**Comment by mathstuf** [comment]
```diff
% diff old.diff new.diff
--- old.diff    2018-02-02 15:44:02.933211402 -0500
+++ new.diff    2018-02-02 15:44:04.632264042 -0500
@@ -288,10 +288,10 @@
  
            std::pair<int, int> from_to;
 diff --git a/include/diy/io/block.hpp b/include/diy/io/block.hpp
-index 05e45a80..baf54a4b 100644
+index 08af9558..7b08ba23 100644
 --- a/include/diy/io/block.hpp
 +++ b/include/diy/io/block.hpp
-@@ -95,8 +95,7 @@ namespace io
+@@ -92,8 +92,7 @@ namespace io
  
      offset_t  start = 0, shift;
      std::vector<GidOffsetCount>     offset_counts;
@@ -301,7 +301,7 @@
      {
        offset_t count = 0,
                 offset;
-@@ -140,12 +139,12 @@ namespace io
+@@ -137,12 +136,12 @@ namespace io
        std::vector<GidOffsetCount>  all_offset_counts;
        for (unsigned i = 0; i < gathered_offset_count_buffers.size(); ++i)
        {
@@ -320,7 +320,7 @@
        }
        std::sort(all_offset_counts.begin(), all_offset_counts.end());        // sorts by gid
  
-@@ -338,12 +337,14 @@ namespace split
+@@ -333,12 +332,14 @@ namespace split
  
      // load the extra buffer and size
      size_t          size;
@@ -342,7 +342,7 @@
      // Get local gids from assigner
      assigner.set_nblocks(size);
 diff --git a/include/diy/master.hpp b/include/diy/master.hpp
-index 4a8f8658..861c19d2 100644
+index fb1e2656..84e556a8 100644
 --- a/include/diy/master.hpp
 +++ b/include/diy/master.hpp
 @@ -162,15 +162,15 @@ namespace diy
```

**Comment by mrzv** [comment]
Ah, Ok. Good. I think it was some Travis problem. Let me see if the new tests pass on `master`, but I think it's all good. Thanks and sorry for the trouble.

**Pull request merged**
