### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by utkarshayachit**
fixes to get diy building and tests passing on the following configurations:

1. Windows 7, MSCV 2015, 64-bit, no-mpi
2. Windows 7, MSCV 2015, 64-bit, msmpi (io tests fails)

### CODE REVIEW

**Comment by utkarshayachit** [comment]
@mrzv for the io-test, which uses MPIIO, my suspicion is that it's due to some bug in Windows MPI (potentially related to [this](https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/607988)).

Also, for now I am disabling tthread on Windows. I saw your comment about using C++11 standard components to replace it. If you want to expand on your thoughts there, I can take a stab if you want. Let me know.

**Comment by mrzv** [comment]
Where do you see tthread? I thought I switched everything to C++11 threading, when we went to DIY 3 (the first C++11 version, although we sort of stopped versioning things explicitly).

**Comment by mrzv** [comment]
Also, have you ever used [AppVeyor](https://www.appveyor.com/)? It would be nice to have Windows tests as part of the GitHub PRs.

**Comment by utkarshayachit** [comment]
> Where do you see tthread? 

See `include/diy/thread.hpp`, it has the following:
```
    // TODO: replace with our own implementation using std::atomic_flag
    using fast_mutex = tthread::fast_mutex;
```

**Comment by utkarshayachit** [comment]
> have you ever used AppVeyor?

No, I have not, but yea, would be nice indeed. Let me know if you want me to look into it.

**Comment by mrzv** [comment]
Ah, I forgot about `fast_mutex`. I guess it should be pretty straight-forward to implement our own version, using [std::atomic_flag](http://en.cppreference.com/w/cpp/atomic/atomic_flag), like the comment says. (Just flip the flag to lock and unlock.) On the other hand, you could also just use a normal [std::mutex](http://en.cppreference.com/w/cpp/thread/mutex), if it's an issue --- I don't feel strongly about it; it was probably one of those premature optimizations. Does the TinyThread implementation of `fast_mutex` not work on Windows?

**Comment by mrzv** [comment]
Regarding AppVeyor, it would be great, if you have cycles for it. I'm afraid that without a Windows box, I don't stand a chance to configure it.

**Comment by utkarshayachit** [comment]
Will do. Not sure when I can get to it as I am traveling this weekend, but I will put it on my plate.

**Comment by mrzv** [comment]
Thanks! No rush on my end. I'll probably merge this PR without it, but ideally we add AppVeyor support nonetheless.

**Comment by mrzv** [comment]
@utkarshayachit Related to the `io-test` issue. I made a change to `tests/io.cpp` (it's in PR #62). Turns out it was segfaulting on my Linux box, without me noticing. Can you see if it also fixes the problem on Windows, by any chance? It's probably unrelated, but it's worth checking anyway. (No rush: whenever you have time.)

**Comment by utkarshayachit** [comment]
@mrzv will do.

**Pull request merged**
